### ISSUE TITLE
Understanding n-level-bias parameter defaults value

### ISSUE THREAD

**Issue by alexpron** [daviddmc/NeSVoR#1]
Hello, 

thanks for developing and making available nesvor. I had a question regarding the n-level-bias parameter of the reconstruct command
+ what was the exact meaning of the n-level-bias  ?
+ its default value is set to 0: does this mean bias field is not corrected by default ? Or does it mean only level 0 of the hasgrid is used to estimate the bias ?

![image](https://user-images.githubusercontent.com/45215023/221151355-ef6859c3-5b3c-412e-81ee-4f95749de977.png)

Best,
Alex

**Comment by daviddmc** [comment]
Hi Alex,

n_levels_bias = 0 means the bias field module is disabled. If the inhomogeneity of the data is small or bias field correction methods, e.g., N4, are applied, setting n_levels_bias = 0 would make the reconstruction more efficient and more stable.

**Comment by alexpron** [comment]
Hello @daviddmc,
Thank you again for your latest reply, I am reopening the issue to dig a bit further on the value of n_levels_bias:
I would like to know which value you used in the nesvor paper and which value you would recommend to correct the bias of  strong bias acquisition
Best, 
Alex

**Comment by daviddmc** [comment]
Hi, I usually set n_levels_bias = 1 or 2 for our own data. Setting n_levels_bias too high would make the algorithm unstable.
I haven't tried the method on data with a strong bias field. I guess you can first apply a bias field correction method such as N4, and then reconstruct with n_levels_bias = 1 or 2.

**Comment by alexpron** [comment]
Hello, thanks for your reply. I ll try that :). 
Best Alex
