### ISSUE TITLE
Three facets of data

### ISSUE THREAD

**Issue by LJJson** [daviddmc/NeSVoR#12]
Dear @daviddmc,

I have information on three facets of a site with specific location coordinates. I was wondering, can we try the program directly with data from other organs.

Thanks!

**Comment by daviddmc** [comment]
Hi @LJJson, do you mean you have stacks of images of another organ? The algorithm should be able to handle generic grayscale data except that SVoRT and segmentation only work for fetal brain data.

**Comment by LJJson** [comment]
#thanks for your reply， yes we  have some  MRI from  another organs , We have processed all these data in a unified coordinate system, and we want to achieve multiple facets (sag,tra,ax) to synthesize a high-resolution surface. It's like an SVR step. I wonder if your project has a similar feature. I have tried to run online fetal data, but it seems that I need to use your last registration project. But what I want to say is that our data all have accurate pixel coordinate information, I don't know whether this step of registration can be omitted. Thank you for your patience, I wish you a happy life.

**Comment by daviddmc** [comment]
If you want to disable registration, you may set `--registration none`.

**Comment by LJJson** [comment]
thanks！  ， I will try  it.
