### ISSUE TITLE
Wrong Phantom in tests/slice_acquisition

### ISSUE THREAD

**Issue by Edenzzzz** [daviddmc/NeSVoR#13]
Hi,
I tested both versions of Phantom in the code "modified-shepp-logan" and "shepp_logan" generated by phantom3d.py, and the outputs are completely off. Please consider replacing it with the correct Phantom.
![image](https://github.com/daviddmc/NeSVoR/assets/87317405/bf279f6e-6306-4cdf-83e8-45a8e2f546cd)

**Comment by daviddmc** [comment]
Thanks for letting me know. It is a problem related to the np.arange used to generate the coordinates.
