### ISSUE TITLE
Visualizing learnt hash grid at different level

### ISSUE THREAD

**Issue by alexpron** [daviddmc/NeSVoR#3]
Dear @daviddmc,
I was trying to reproduce the visualization you made Fig.13 in the nesvor paper, i.e. the different levels of the learnt hashgrid. However I have not managed so far to obtain similar visualization. Is there some piece of code included in nesvor I could use to do that. If not, may you indicate me how to proceed ? So far I obtained patterns that are replicated, i.e. one brain then half a brain superimposed in the same figure, which seems weird.
Best,
Alex

**Comment by daviddmc** [comment]
Hi, seeing replicated brains is kind of expected due to the mod operation in the hash function.
To get the results in the paper you would need to apply to brain mask to the hashgrid image.
