### ISSUE TITLE
ROI in the data is too large for SVoRT

### ISSUE THREAD

**Issue by m-dannecker** [daviddmc/NeSVoR#6]
Dear @daviddmc,

Thanks for making this code public! 
I am currently trying to reconstruct an adult brain from HCP using nesvor. However, I get the warning "[WARNING] ROI in the data is too large for SVoRT" when I want to pre-register the slices via SVoRT. The model then skips SVoRT and resorts to regular stack registration. I'm using 3 Stacks with spacing[1.25, 1.25, 3.3], resulting in a rough dimension of [170, 150, 55]. Would you happen to know how to handle this problem? 

Thanks!

**Comment by m-dannecker** [comment]
Thanks for the quick reply! 
Good to know. I guess the stack transformation provides a better metric then, as it always proceeds with stack transformation. Regarding air around the brain: the HCP brains come pre-masked, so that should not be a problem, right?

**Comment by daviddmc** [comment]
By default, the command runs both SVoRT and stack-to-stack registration and chooses the method with higher NCC consistency.
If the interslice misalignment is relatively small, it would prefer stack registration.

**Comment by m-dannecker** [comment]
Alright, thanks for the clarification!
