### ISSUE TITLE
Wrong checkpoint for DynUNet

### ISSUE THREAD

**Issue by Edenzzzz** [daviddmc/NeSVoR#7]
I ran `nesvor segment-stack --input-stacks volumes/case2_day1_stack.nii.gz --output-stack-masks volumes/case2_day1_mask.nii.gz` but the downloaded checkpoint (nesvor/preprocessing/masking/brain_segmentation.py)  is completely wrong and all keys are unexpected.

![image](https://github.com/daviddmc/NeSVoR/assets/87317405/1f2a7410-f245-493e-ae4a-7e49c318a50f)

**Comment by daviddmc** [comment]
Hi @Edenzzzz, did you use the docker or install NeSVoR from source? The segmentation model (i.e., MONAIfbs) uses [monai v0.3.0](https://github.com/gift-surg/MONAIfbs/blob/main/requirements.txt). Could you check if your version of monai is too high?

**Comment by Edenzzzz** [comment]
Thanks for the speedy reply. I installed from source with MONAI 0.4. Switching to V0.3 works fine.
